import time
from datetime import datetime, timezone
from database import get_db_session, TicketModel, init_db

def seed_rich_demo_tickets():
    init_db()
    session = get_db_session()
    try:
        # Clear existing tickets so we can reseed fresh, rich demo data
        session.query(TicketModel).delete()
        session.commit()

        now = time.time()
        iso_now = datetime.now(timezone.utc).isoformat()

        demo_tickets = [
            # --- ROAD INFRASTRUCTURE (7 items) ---
            TicketModel(
                id="TICK-1001",
                problem="Severe Pothole (Depth > 8cm)",
                confidence=0.95,
                latitude=17.4325,
                longitude=78.4072,
                votes=26,
                status="ASSIGNED_TO_CONTRACTOR",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 14,
                sla_deadline_timestamp=now + 3600 * 34,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                plan_of_action="Cold mix bitumen compaction crew scheduled for 8:00 PM off-peak repair.",
            ),
            TicketModel(
                id="TICK-1002",
                problem="Deep Road Crater & Surface Subsidence",
                confidence=0.92,
                latitude=17.4447,
                longitude=78.4664,
                votes=38,
                status="ESCALATED_ZONAL",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 52,
                sla_deadline_timestamp=now - 3600 * 4,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                is_escalated=True,
                escalated_at=iso_now,
                escalation_reason="48-Hour SLA exceeded without contractor proof. Priority Zonal Action Required.",
            ),
            TicketModel(
                id="TICK-1003",
                problem="Waterlogging & Blocked Storm Drain",
                confidence=0.97,
                latitude=17.4399,
                longitude=78.4983,
                votes=18,
                status="RESOLVED",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 32,
                sla_deadline_timestamp=now + 3600 * 16,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                proof_image_filename="sample_pothole_after.jpg",
                resolved_at=iso_now,
                resolution_summary="Silt trap cleared and surface laid with hot asphalt overlay. Full drainage restored.",
            ),
            TicketModel(
                id="TICK-1004",
                problem="Pothole Cluster & Broken Bitumen Surface",
                confidence=0.91,
                latitude=17.4478,
                longitude=78.3912,
                votes=21,
                status="IN_PROGRESS",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 18,
                sla_deadline_timestamp=now + 3600 * 30,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                plan_of_action="Road milling machine deployed. Patching in progress.",
            ),
            TicketModel(
                id="TICK-1005",
                problem="Damaged Concrete Median Divider",
                confidence=0.88,
                latitude=17.4401,
                longitude=78.3489,
                votes=14,
                status="IN_PROGRESS",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 22,
                sla_deadline_timestamp=now + 3600 * 26,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                plan_of_action="Pre-cast median curb blocks delivered. Re-alignment underway.",
            ),
            TicketModel(
                id="TICK-1006",
                problem="Sunken Manhole Cover & Asphalt Lip",
                confidence=0.94,
                latitude=17.4852,
                longitude=78.4069,
                votes=31,
                status="RESOLVED",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 40,
                sla_deadline_timestamp=now + 3600 * 8,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                proof_image_filename="sample_pothole_after.jpg",
                resolved_at=iso_now,
                resolution_summary="Manhole frame raised to grade and sealed with polymer modified bitumen.",
            ),
            TicketModel(
                id="TICK-1007",
                problem="Asphalt Surface Alligator Cracking",
                confidence=0.89,
                latitude=17.4339,
                longitude=78.4485,
                votes=12,
                status="ASSIGNED_TO_CONTRACTOR",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 10,
                sla_deadline_timestamp=now + 3600 * 38,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
            ),

            # --- TRAFFIC FLOW & CONGESTION (5 items) ---
            TicketModel(
                id="TICK-2001",
                problem="Traffic Bottleneck & Illegal Commercial Loading",
                confidence=0.90,
                latitude=17.4504,
                longitude=78.3808,
                votes=42,
                status="IN_PROGRESS",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 25,
                sla_deadline_timestamp=now + 3600 * 23,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                plan_of_action="Traffic police marshals assigned to clear curb encroachment.",
            ),
            TicketModel(
                id="TICK-2002",
                problem="Signal Timing Desync Causing Junction Gridlock",
                confidence=0.87,
                latitude=17.4248,
                longitude=78.4529,
                votes=35,
                status="ASSIGNED_TO_CONTRACTOR",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 15,
                sla_deadline_timestamp=now + 3600 * 33,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
            ),
            TicketModel(
                id="TICK-2003",
                problem="Bus Bay Illegal Auto Stand Choke Point",
                confidence=0.93,
                latitude=17.3949,
                longitude=78.4431,
                votes=47,
                status="ESCALATED_ZONAL",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 55,
                sla_deadline_timestamp=now - 3600 * 7,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                is_escalated=True,
                escalated_at=iso_now,
                escalation_reason="Severe public transit delay reported by TSRTC bus telemetry for 48h.",
            ),
            TicketModel(
                id="TICK-2004",
                problem="Narrow U-Turn Road Friction Bottleneck",
                confidence=0.86,
                latitude=17.4682,
                longitude=78.3621,
                votes=19,
                status="RESOLVED",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 38,
                sla_deadline_timestamp=now + 3600 * 10,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                proof_image_filename="sample_pothole_after.jpg",
                resolved_at=iso_now,
                resolution_summary="Flexible bollards placed to streamline turning radius and eliminate friction.",
            ),
            TicketModel(
                id="TICK-2005",
                problem="Defective Traffic Blinkers at Arterial Crossroad",
                confidence=0.91,
                latitude=17.3688,
                longitude=78.5247,
                votes=16,
                status="IN_PROGRESS",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 16,
                sla_deadline_timestamp=now + 3600 * 32,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                plan_of_action="Traffic electronics maintenance technician dispatched.",
            ),

            # --- PEDESTRIAN & SAFETY INTELLIGENCE (5 items) ---
            TicketModel(
                id="TICK-3001",
                problem="Missing Pedestrian Zebra & School Crossing Hazard",
                confidence=0.96,
                latitude=17.3616,
                longitude=78.4747,
                votes=54,
                status="ASSIGNED_TO_CONTRACTOR",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 12,
                sla_deadline_timestamp=now + 3600 * 36,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
            ),
            TicketModel(
                id="TICK-3002",
                problem="Dark Street Segment & Blind Pedestrian Crossing",
                confidence=0.94,
                latitude=17.4192,
                longitude=78.4481,
                votes=39,
                status="RESOLVED",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 44,
                sla_deadline_timestamp=now + 3600 * 4,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                proof_image_filename="sample_pothole_after.jpg",
                resolved_at=iso_now,
                resolution_summary="High-mast LED luminaire repaired and retro-reflective warning signs posted.",
            ),
            TicketModel(
                id="TICK-3003",
                problem="Unprotected Deep Excavation Trench on Roadside",
                confidence=0.98,
                latitude=17.3998,
                longitude=78.4114,
                votes=63,
                status="ESCALATED_ZONAL",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 50,
                sla_deadline_timestamp=now - 3600 * 2,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                is_escalated=True,
                escalated_at=iso_now,
                escalation_reason="Severe public safety hazard near school route. Red barricading missing.",
            ),
            TicketModel(
                id="TICK-3004",
                problem="School Zone Lack of Speed Calming Table",
                confidence=0.90,
                latitude=17.4411,
                longitude=78.5019,
                votes=28,
                status="IN_PROGRESS",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 20,
                sla_deadline_timestamp=now + 3600 * 28,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
                plan_of_action="Rubberized thermoplastic speed table construction approved and scheduled.",
            ),
            TicketModel(
                id="TICK-3005",
                problem="High-Speed Merge Conflict & Missing Signboard",
                confidence=0.92,
                latitude=17.4123,
                longitude=78.3391,
                votes=22,
                status="ASSIGNED_TO_CONTRACTOR",
                contractor_email="ee-circle12@ghmc.gov.in",
                escalation_email="zc-central@ghmc.gov.in",
                created_at=iso_now,
                created_timestamp=now - 3600 * 8,
                sla_deadline_timestamp=now + 3600 * 40,
                last_voted_at=iso_now,
                evidence_image_filename="sample_pothole_before.jpg",
            ),
        ]

        session.add_all(demo_tickets)
        session.commit()
        print(f"[+] Successfully seeded {len(demo_tickets)} rich Hyderabad municipal defect tickets!")
    finally:
        session.close()

if __name__ == "__main__":
    seed_rich_demo_tickets()
